#!/usr/bin/env python3
import argparse
import json
import os
import shlex
import subprocess
import sys
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple


DEFAULT_MODEL_DIR = "/home/spark2/models/hf/nvidia/GLM-5.2-NVFP4"
SCHEMA = "sparkpipe.glm52.prompt_pipeline_input.v1"


class PromptInputFailure(Exception):
    pass


def parse_token_ids(text: str) -> List[int]:
    result: List[int] = []
    for raw_item in text.replace("\n", ",").replace(" ", ",").split(","):
        item = raw_item.strip()
        if item == "":
            continue
        try:
            token_id = int(item, 10)
        except ValueError as exc:
            raise PromptInputFailure(f"invalid token id: {item}") from exc
        if token_id < 0:
            raise PromptInputFailure(f"negative token id: {token_id}")
        result.append(token_id)
    if not result:
        raise PromptInputFailure("token id list is empty")
    return result


def load_prompt(args: argparse.Namespace) -> str:
    if args.prompt is not None:
        return args.prompt
    if args.prompt_file is not None:
        return Path(args.prompt_file).read_text(encoding="utf-8")
    raise PromptInputFailure("set --prompt, --prompt-file, or --token-ids")


def tokenize_with_transformers(model_dir: Path, prompt: str, chat: bool, system_prompt: Optional[str], add_generation_prompt: bool) -> Tuple[List[int], str]:
    try:
        from transformers import AutoTokenizer  # type: ignore
    except ImportError as exc:
        raise PromptInputFailure("transformers is not installed") from exc
    tokenizer = AutoTokenizer.from_pretrained(str(model_dir), trust_remote_code=True, local_files_only=True)
    if chat:
        messages: List[Dict[str, str]] = []
        if system_prompt is not None:
            messages.append({"role": "system", "content": system_prompt})
        messages.append({"role": "user", "content": prompt})
        token_ids = tokenizer.apply_chat_template(messages, tokenize=True, add_generation_prompt=add_generation_prompt)
        return [int(token_id) for token_id in token_ids], "transformers_chat_template"
    encoded = tokenizer(prompt, add_special_tokens=True)
    return [int(token_id) for token_id in encoded["input_ids"]], "transformers_encode"


def tokenize_with_tokenizers(model_dir: Path, prompt: str, chat: bool) -> Tuple[List[int], str]:
    if chat:
        raise PromptInputFailure("chat template mode needs transformers for now")
    tokenizer_path = model_dir / "tokenizer.json"
    if not tokenizer_path.is_file():
        raise PromptInputFailure(f"missing tokenizer.json: {tokenizer_path}")
    try:
        from tokenizers import Tokenizer  # type: ignore
    except ImportError as exc:
        raise PromptInputFailure("tokenizers is not installed") from exc
    tokenizer = Tokenizer.from_file(str(tokenizer_path))
    encoded = tokenizer.encode(prompt)
    return [int(token_id) for token_id in encoded.ids], "tokenizers_json"


def tokenize_prompt(args: argparse.Namespace, model_dir: Path) -> Tuple[List[int], str]:
    if args.token_ids is not None:
        return parse_token_ids(args.token_ids), "explicit_token_ids"
    prompt = load_prompt(args)
    errors: List[str] = []
    for tokenizer_fn in (tokenize_with_transformers,):
        try:
            return tokenizer_fn(model_dir, prompt, args.chat, args.system_prompt, not args.no_add_generation_prompt)
        except PromptInputFailure as exc:
            errors.append(str(exc))
    try:
        return tokenize_with_tokenizers(model_dir, prompt, args.chat)
    except PromptInputFailure as exc:
        errors.append(str(exc))
    raise PromptInputFailure("unable to tokenize prompt locally: " + "; ".join(errors))


def choose_bootstrap_token(token_ids: List[int], policy: str) -> int:
    if policy == "last":
        return token_ids[-1]
    if policy == "first":
        return token_ids[0]
    raise PromptInputFailure(f"unsupported bootstrap policy: {policy}")


def write_env_file(path: Path, values: Dict[str, str]) -> None:
    lines = ["# generated by tools/glm52_prompt_pipeline_input.py"]
    for key in sorted(values):
        lines.append(f"export {key}={shlex.quote(values[key])}")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def write_artifacts(args: argparse.Namespace, token_ids: List[int], tokenizer_kind: str, bootstrap_token: int, model_dir: Path) -> Dict[str, Path]:
    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    prompt_text = "" if args.token_ids is not None else load_prompt(args)
    token_json = output_dir / "prompt_tokens.json"
    token_txt = output_dir / "prompt_tokens.txt"
    prompt_txt = output_dir / "prompt.txt"
    env_path = output_dir / "pipeline_env.sh"
    pipeline_output_dir = Path(args.pipeline_output_dir) if args.pipeline_output_dir is not None else output_dir / "pipeline_run"
    payload: Dict[str, Any] = {
        "schema": SCHEMA,
        "model_dir": str(model_dir),
        "tokenizer": tokenizer_kind,
        "prompt": prompt_text,
        "token_count": len(token_ids),
        "token_ids": token_ids,
        "bootstrap_token_id": bootstrap_token,
        "bootstrap_policy": args.bootstrap_token,
        "pipeline_semantics": "single-token bootstrap only; no prompt KV prefill context yet",
    }
    token_json.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    token_txt.write_text("\n".join(str(token_id) for token_id in token_ids) + "\n", encoding="utf-8")
    prompt_txt.write_text(prompt_text, encoding="utf-8")
    write_env_file(env_path, {
        "GLM52_LOCAL_PIPELINE_INPUT_TOKEN_ID": str(bootstrap_token),
        "GLM52_LOCAL_PIPELINE_OUTPUT_DIR": str(pipeline_output_dir),
        "GLM52_PROMPT_BOOTSTRAP_MODE": "last_or_first_prompt_token_without_prefill_kv",
        "GLM52_PROMPT_TOKEN_ARTIFACT": str(token_json),
        "GLM52_PROMPT_TOKEN_COUNT": str(len(token_ids)),
    })
    return {
        "token_json": token_json,
        "token_txt": token_txt,
        "prompt_txt": prompt_txt,
        "env": env_path,
        "pipeline_output_dir": pipeline_output_dir,
    }


def run_pipeline(args: argparse.Namespace, artifacts: Dict[str, Path], bootstrap_token: int) -> int:
    root = Path(__file__).resolve().parents[1]
    script = Path(args.pipeline_script)
    if not script.is_absolute():
        script = root / script
    if not script.is_file():
        raise PromptInputFailure(f"missing pipeline script: {script}")
    env = os.environ.copy()
    env["GLM52_LOCAL_PIPELINE_INPUT_TOKEN_ID"] = str(bootstrap_token)
    env["GLM52_LOCAL_PIPELINE_OUTPUT_DIR"] = str(artifacts["pipeline_output_dir"])
    env["GLM52_PROMPT_TOKEN_ARTIFACT"] = str(artifacts["token_json"])
    env["GLM52_PROMPT_TOKEN_COUNT"] = str(len(json.loads(artifacts["token_json"].read_text(encoding="utf-8"))["token_ids"]))
    return subprocess.run([str(script)], cwd=str(root), env=env, check=False).returncode


def parse_args(argv: List[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Tokenize a GLM-5.2 prompt and feed the current single-token local pipeline bootstrap.")
    source = parser.add_mutually_exclusive_group(required=True)
    source.add_argument("--prompt")
    source.add_argument("--prompt-file")
    source.add_argument("--token-ids", help="Comma or whitespace separated token ids; skips tokenizer dependency.")
    parser.add_argument("--model-dir", default=os.environ.get("GLM52_MODEL_DIR", DEFAULT_MODEL_DIR))
    parser.add_argument("--output-dir", default="build/glm52_prompt_pipeline_input")
    parser.add_argument("--pipeline-output-dir")
    parser.add_argument("--pipeline-script", default="tools/glm52_spark2_local_pipeline_gate.sh")
    parser.add_argument("--bootstrap-token", choices=("last", "first"), default="last")
    parser.add_argument("--chat", action="store_true", help="Use the HF chat template when transformers is available.")
    parser.add_argument("--system-prompt")
    parser.add_argument("--no-add-generation-prompt", action="store_true")
    parser.add_argument("--run-pipeline", action="store_true")
    return parser.parse_args(argv)


def main(argv: List[str]) -> int:
    try:
        args = parse_args(argv)
        model_dir = Path(args.model_dir)
        token_ids, tokenizer_kind = tokenize_prompt(args, model_dir)
        bootstrap_token = choose_bootstrap_token(token_ids, args.bootstrap_token)
        artifacts = write_artifacts(args, token_ids, tokenizer_kind, bootstrap_token, model_dir)
        print(f"glm52_prompt_tokenizer={tokenizer_kind}")
        print(f"glm52_prompt_token_count={len(token_ids)}")
        print(f"glm52_prompt_bootstrap_token={bootstrap_token}")
        print(f"glm52_prompt_tokens_json={artifacts['token_json']}")
        print(f"glm52_prompt_pipeline_env={artifacts['env']}")
        print("glm52_prompt_pipeline_semantics=single_token_bootstrap_no_prefill_kv")
        if args.run_pipeline:
            return run_pipeline(args, artifacts, bootstrap_token)
        return 0
    except PromptInputFailure as exc:
        print(f"glm52_prompt_pipeline_input_error={exc}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
